# Generated by Django 4.2.7 on 2023-12-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_profile_pic1_alter_profile_pic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
